// <auto-generated />
namespace QLDV1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class chang_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chang_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202104281634327_chang_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
